/* ==========================================================================
   Nivelle — catalog layer
   Shared helpers over window.PRODUCT_CATALOG (generated by
   scripts/sync-shopify.mjs from the live Shopify store) plus the grid
   renderers used by the home and shop pages.

   Every buy action links straight to a Shopify cart permalink, so checkout
   happens on the store itself — this site holds no cart state of its own.
   ========================================================================== */
(function () {
  'use strict';

  var CATALOG = window.PRODUCT_CATALOG || [];
  var STORE = window.SHOPIFY_STORE || { domain: '', cartUrl: '#' };

  /* Swatch colours for the option values the store actually uses. Anything
     new falls back to a neutral chip rather than guessing wrong. */
  var COLOR_HEX = {
    White: '#F2EFE9',
    Black: '#1c1917',
    Gray: '#8B8985',
    Grey: '#8B8985',
    Brown: '#6B4226',
    Pink: '#E2A9BC',
    Claret: '#7B2D3B',
    'Dark Coffee': '#3E2A20',
    Purple: '#6B4E9B',
  };

  function money(amount) {
    return '$' + Number(amount).toFixed(2);
  }

  function imageUrl(url, width) {
    if (!url) return '';
    return url + (url.indexOf('?') > -1 ? '&' : '?') + 'width=' + width;
  }

  function cartUrl(variantId, qty) {
    return 'https://' + STORE.domain + '/cart/' + variantId + ':' + (qty || 1);
  }

  function colorHex(name) {
    return COLOR_HEX[name] || '#CFC7BA';
  }

  function discountPercent(product) {
    if (!product.was || product.was <= product.price) return 0;
    return Math.round((1 - product.price / product.was) * 100);
  }

  function firstAvailableVariant(product) {
    for (var i = 0; i < product.variants.length; i++) {
      if (product.variants[i].available) return product.variants[i];
    }
    return product.variants[0];
  }

  function colorValues(product) {
    var option = product.options.filter(function (o) {
      return /colou?r/i.test(o.name);
    })[0];
    return option ? option.values : [];
  }

  function stockLine(product) {
    var total = product.variants.length;
    var inStock = product.variants.filter(function (v) {
      return v.available;
    }).length;
    if (inStock === 0) return 'Sold out';
    if (inStock < total) return inStock + ' of ' + total + ' colours in stock';
    return '';
  }

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  /* ------------------------------------------------------------------ */
  /* Card markup                                                        */
  /* ------------------------------------------------------------------ */
  function productCardHTML(product) {
    var variant = firstAvailableVariant(product);
    var href = 'product.html?slug=' + encodeURIComponent(product.slug);
    var name = escapeHtml(product.name);
    var image = product.images[0];
    var discount = discountPercent(product);
    var stock = stockLine(product);
    var colors = colorValues(product);

    var badge = '';
    if (discount > 0) {
      badge = '<span class="product-badge gold">Save ' + discount + '%</span>';
    }

    var swatches = colors.length
      ? '<div class="product-swatches" aria-hidden="true">' +
        colors
          .map(function (c) {
            return '<span class="swatch" style="background:' + colorHex(c) + '" title="' + escapeHtml(c) + '"></span>';
          })
          .join('') +
        '</div>'
      : '';

    var priceHtml =
      '<span>' +
      money(product.price) +
      '</span>' +
      (product.was && product.was > product.price ? '<span class="was">' + money(product.was) + '</span>' : '');

    var buy = product.available
      ? '<a class="btn btn-dark" href="' +
        cartUrl(variant.id, 1) +
        '" data-buy-link>Add to bag</a>'
      : '<a class="btn btn-dark" href="' + escapeHtml(product.storeUrl || STORE.cartUrl) + '">Sold out &mdash; view store</a>';

    return (
      '<article class="product-card" data-reveal data-slug="' +
      escapeHtml(product.slug) +
      '" data-price="' +
      product.price +
      '" data-colors="' +
      escapeHtml(colors.join('|')) +
      '" data-available="' +
      product.available +
      '">' +
      '<div class="product-media">' +
      badge +
      '<a href="' +
      href +
      '" class="product-media-link" aria-label="View ' +
      name +
      '">' +
      (image
        ? '<img src="' +
          imageUrl(image.url, 700) +
          '" alt="' +
          escapeHtml(image.alt || product.name) +
          '" width="' +
          image.width +
          '" height="' +
          image.height +
          '" loading="lazy" decoding="async">'
        : '') +
      '</a>' +
      '<span class="product-quickadd">' +
      buy +
      '</span>' +
      '</div>' +
      '<div class="product-info">' +
      '<span class="product-category">' +
      (colors.length ? colors.length + ' colourways' : escapeHtml(product.category)) +
      '</span>' +
      '<h3><a href="' +
      href +
      '">' +
      name +
      '</a></h3>' +
      '<div class="product-price">' +
      priceHtml +
      '</div>' +
      (stock ? '<p class="stock-note">' + stock + '</p>' : '') +
      swatches +
      '</div>' +
      '</article>'
    );
  }

  function renderGrid(container, products) {
    if (!container) return;
    container.innerHTML = products.map(productCardHTML).join('');
    if (window.Nivelle && window.Nivelle.observeReveals) {
      window.Nivelle.observeReveals(container);
    }
  }

  /* ------------------------------------------------------------------ */
  /* Store-wide links (header bag, sticky bar, hero CTA)                */
  /* ------------------------------------------------------------------ */
  document.querySelectorAll('[data-store-cart]').forEach(function (el) {
    el.setAttribute('href', STORE.cartUrl);
  });

  var featured = document.querySelector('[data-featured-grid]');
  if (featured) {
    var limit = parseInt(featured.getAttribute('data-featured-grid'), 10) || CATALOG.length;
    renderGrid(featured, CATALOG.slice(0, limit));
  }

  /* ------------------------------------------------------------------ */
  /* Colourway strip — one tile per variant, straight from the store     */
  /* ------------------------------------------------------------------ */
  var strip = document.querySelector('[data-colorway-strip]');
  if (strip) {
    var tiles = [];
    CATALOG.forEach(function (product) {
      product.variants.forEach(function (variant) {
        if (!variant.image) return;
        tiles.push(
          '<a class="gallery-item" data-reveal="wipe" href="product.html?slug=' +
            encodeURIComponent(product.slug) +
            '" aria-label="' +
            escapeHtml(product.name + ' in ' + variant.title) +
            '">' +
            '<img src="' +
            imageUrl(variant.image, 400) +
            '" alt="' +
            escapeHtml(product.name + ' in ' + variant.title) +
            '" loading="lazy" decoding="async">' +
            '<span class="handle">' +
            escapeHtml(variant.title) +
            (variant.available ? '' : ' &middot; sold out') +
            '</span>' +
            '</a>'
        );
      });
    });
    strip.innerHTML = tiles.join('');
    if (window.Nivelle && window.Nivelle.observeReveals) {
      window.Nivelle.observeReveals(strip);
    }
  }

  window.NivelleCatalog = {
    products: CATALOG,
    store: STORE,
    money: money,
    imageUrl: imageUrl,
    cartUrl: cartUrl,
    colorHex: colorHex,
    colorValues: colorValues,
    discountPercent: discountPercent,
    firstAvailableVariant: firstAvailableVariant,
    stockLine: stockLine,
    escapeHtml: escapeHtml,
    productCardHTML: productCardHTML,
    renderGrid: renderGrid,
  };
})();
